version: '3.1'

services:
  lope_anno:
    restart: always
    build: . 
    ports:
      - '8001:8001'
    volumes:
      - "./dbs:/lope.anno/dbs"
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
